readme.md

Replaces suggested usage references to `line-length` with `natural`.
Fixes #14
n/a

docs: suggest natural, not line-length, in readme.md

---

docs/rules/sort-objects.md
index.ts
rules/sort-objects.ts
test/sort-objects.test.ts
typings/index.ts
utils/get-node-range.ts
utils/is-partition-comment.ts
utils/make-fixes.ts

We need to add the functionality of separating object properties into logical parts using comments in the code.
Close #22
---

feat: allow separating object properties into logical parts

---

docs/rules/index.md
docs/rules/sort-maps.md
index.ts
readme.md
rules/sort-maps.ts
test/sort-maps.test.ts

Rename `sort-map-elements` rule to `sort-maps`
#32
---

feat!: rename sort-map-elements rule to sort-maps

---

rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-jsx-props.ts
rules/sort-map-elements.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-union-types.ts
test/sort-array-includes.test.ts
test/sort-classes.test.ts
test/sort-enums.test.ts
test/sort-exports.test.ts
test/sort-imports.test.ts
test/sort-interfaces.test.ts
test/sort-jsx-props.test.ts
test/sort-map-elements.test.ts
test/sort-named-exports.test.ts
test/sort-named-imports.test.ts
test/sort-object-types.test.ts
test/sort-objects.test.ts
test/sort-union-types.test.ts

Currently, the default `type` specified in the schema of every rule is `SortType.natural`. This will cause inconsistent behavior. For example,  `"perfectionist/sort-array-includes": "error"` and `"perfectionist/sort-array-includes": ["error", {}]` don't work in the same way. The first one uses alphabetical sorting while the second uses natural sorting.
This PR fixes the default `type` for all rules.
N/A
---

fix: use alphabetical as the default sort type in schemas

---

docs/rules/index.md
docs/rules/sort-astro-attributes.md
index.ts
package.json
pnpm-lock.yaml
readme.md
rules/sort-astro-attributes.ts
rules/sort-jsx-props.ts
rules/sort-svelte-attributes.ts
test/sort-astro-attributes.test.ts
test/sort-svelte-attributes.test.ts

Adds a new rule for sorting attributes in Astro.
#25, #32
---

feat: add sort-astro-attributes rule

---

rules/sort-astro-attributes.ts
rules/sort-classes.ts
rules/sort-imports.ts
rules/sort-jsx-props.ts
rules/sort-svelte-attributes.ts
typings/index.ts
utils/get-group-number.ts
utils/group-by.ts
utils/use-groups.ts

Refactor code of groups.
N/A
---

refactor: add use-groups helper

---

docs/rules/sort-interfaces.md
rules/sort-interfaces.ts
test/sort-interfaces.test.ts

Add `groups` and `custom-groups` option for `sort-intefaces` rule
#29, #32
---

feat: add groups option in sort-interfaces rule

---

docs/rules/sort-object-types.md
rules/sort-interfaces.ts
rules/sort-object-types.ts
test/sort-object-types.test.ts

Add `groups` and `custom-groups` option for `sort-object-types` rule.
#32
---

feat: add groups options in sort-object-types rule

---

rules/sort-imports.ts
test/sort-imports.test.ts

Fix #65
Because `builtinModules` does not includes modules that start with the prefix `node:` you need to check it manually.
---

fix: prefix-only builtin modules are defined as external modules in sort-imports rule

---

rules/sort-imports.ts
test/sort-imports.test.ts

Fix #72 
I changed the group definition sequence to get the correct behavior.
---

fix: side-effect import with an internal pattern are defined as internal module in sort-imports rule

---

docs/rules/sort-objects.md
rules/sort-imports.ts
rules/sort-objects.ts
test/sort-objects.test.ts
utils/get-lines-between.ts

Add `partition-by-new-line` option to `sort-objects` rule.
#86
---

feat: add partition by new line option to sort-objects rule

---

docs/rules/sort-imports.md

note on usage of prettier-plugin-sort-imports in sort-imports conflicts
I got this conflicts and spent hours trying to figure this out. Hopefully this note will help others avoid this.
---

docs: note on usage of prettier-plugin-sort-imports in sort-imports conflicts

---

docs/rules/sort-classes.md
rules/sort-classes.ts
test/sort-classes.test.ts

Closes #93!
This PR adds support for grouping decorated fields and methods separately, optionally specifying their accessibility.
---

feat(sort-classes): add decorators support

---

docs/rules/sort-enums.md
rules/sort-enums.ts
test/sort-enums.test.ts

feat(sort-enums): add `partition-by-comment` option

---

docs/rules/sort-named-exports.md
docs/rules/sort-named-imports.md
rules/sort-named-exports.ts
rules/sort-named-imports.ts
test/sort-named-exports.test.ts
test/sort-named-imports.test.ts
typings/index.ts

This PR adds the `group-kind` option to `sort-named-imports` and `sort-named-exports` rules, solving https://github.com/azat-io/eslint-plugin-perfectionist/issues/114
This allows users to group inline named type imports before or after value named imports.
This option has three possible values: `mixed`, `values-first`, and `types-first`.
```tsx
// group-kind: mixed (default, current behavior)
import { A, type B, C, type D} from 'rurouni-kenshin'
// group-kind: values-first
import { A, C, type B, type D } from 'rurouni-kenshin'
// group-kind: types-first
import { type B, type D, A, C } from 'rurouni-kenshin'
```
---

feat: adds `group-kind` option on `sort-named-imports` and `sort-named-exports`

---

docs/rules/sort-interfaces.md
rules/sort-interfaces.ts
test/sort-interfaces.test.ts
typings/index.ts
utils/is-member-optional.ts

This PR adds the `optionalityOrder` option to the `sort-interfaces` rule.
This option has three possible values: `ignore`, `optional-first`, `required-first`.
If the `required-first` option is selected, then before any sorting/grouping configurations, we ensure that the members array has all its required elements first and all its optional elements second. We then perform the remaining sorting/grouping checks on the required subset and the optional subset.
```json
// .eslintrc.json
{
"custom-groups": {
"callback": "on*"
},
"groups": ["unknown", "callback"],
"optionalityOrder": "required-first"
}
```
❌ Incorrect
```ts
interface ButtonProps {
backgroundColor?: string
label: string
primary?: boolean
size?: 'large' | 'medium' | 'small'
onClick?(): void
}
```
✅ Correct
```ts
interface …
```

feat(sort-interfaces): add `optionalityOrder` option

---

docs/rules/sort-intersection-types.md
index.ts
readme.md
rules/sort-intersection-types.ts
test/sort-intersection-types.test.ts

Fixes #84.
I copy & pasted the existing `sort-union-types` rule, find-and-replaced _"union"_ to _"intersection"_, then updated tests to use `&` intersection types.
I didn't add the `nullable-last` option because I figured that's not a common scenario with intersection types. Maybe I'm wrong there?
---

feat: add sort-intersection-types rule

---

rules/sort-objects.ts
test/sort-objects.test.ts
utils/get-node-parent.ts

fix: sort-objects ignore-pattern add Property type

---

rules/sort-imports.ts
test/sort-imports.test.ts

I noticed a bug when writing some code in a project where I have set up this plugin (thank you by the way, it helps out a lot!). When I wrote a named import but didn't specify anything to be imported it was being considered a side-effect import and moved to the bottom of the list of imports. Turns out there is no way to distinguish a side-effect import from an empty named import from looking at the AST, so the only thing I could think of what to look for a `} from` string in the nodes code to make it not being considered a side-effect import 🙂
Output from [AST explorer](https://astexplorer.net/#/gist/090f7d39fb3be4d37c64d13fccc31156/210c0b4ea656f0eee3406d52b63937f5fc34754f)
---

fix(sort-imports): empty named imports being considered side-effect imports

---

package.json
pnpm-lock.yaml

Fixes #130.
---
- ~[ ] Ideally, include relevant tests that fail without this PR but pass with it.~

fix: allow @typescript-eslint/utils@7

---

docs/rules/sort-imports.md

The docs is showing `siblings` for the `sibling` value which should be `sibling` without `s`.
None

docs: fix typo of sibling

---

package.json
pnpm-lock.yaml

Hi, this PR updates the `astro-eslint-parser` to the stable version v1.0.2.
I was trying to use my astro config eslint with `eslint-plugin-perfectionist` but the package manager is complaining about the missing peer dependency version of `astro-eslint-parser@0.16.0` since I was trying to use the v1.0.2
---

chore: update astro

---

package.json
pnpm-lock.yaml
rules/sort-svelte-attributes.ts

We will update the related Svelte packages.
When adding eslint-plugin-perfectionist to a SvelteKit project created with `npm create svelte@latest`, the following error occurs. Therefore, we will update the related Svelte packages.
```
✝  git/study/eslint-plugin-perfectionist-example  npm install --save-dev eslint-plugin-perfectionist
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-perfectionist-example@0.0.1
npm ERR! Found: svelte-eslint-parser@0.36.0
npm ERR! node_modules/svelte-eslint-parser
npm ERR!   svelte-eslint-parser@">=0.36.0 <1.0.0" from eslint-plugin-svelte@2.39.0
npm ERR!   node_modules/eslint-plugin-svelte
npm ERR!     dev eslint-plugin-svelte@"^2.35.1" from the root project
npm ERR! 
npm ERR! Could not resolve …
```

chore: update svelte

---

docs/rules/sort-classes.md
package.json
rules/sort-classes.ts
test/sort-classes.test.ts
utils/use-groups.ts

Today class ordering doesn't work much for classes that represent database entities. For example, using TypeORM, the ordering of properties changes the order of the columns in the database. To make it easier to use, I propose adding a **custom-groups** functionality already present in other rules such as **sort-objects**.
Configuration: 
```
'perfectionist/sort-classes': [
'error',
{
'custom-groups': {
'entity-id': ['id'],
'entity-timestamps': ['createdAt'],
},
groups: [
'entity-id',
'index-signature',
'static-property',
'private-property',
'property',
'constructor',
'static-method',
'private-method',
'method',
['get-method', 'set-method'],
'unknown',
'entity-timestamps',
],
},
]
```
Input: 
```js
export class TestEntity {
@PrimaryGeneratedColumn('increment')
id: number
@Column()
name: …
```

feat(sort-classes): add custom-group to sort-classes rule

---

docs/content/rules/sort-objects.mdx
rules/sort-objects.ts
test/sort-objects.test.ts

#126
Because `json-schema` does not support `function` type, it is converted through `object`.
---

feat: add custom ignore to enable customizable ignore rule

---

docs/content/rules/sort-intersection-types.mdx
rules/sort-intersection-types.ts
test/sort-intersection-types.test.ts

Support groups from [this rule](https://typescript-eslint.io/rules/sort-type-constituents/#grouporder).
#151
---

feat: add groups option in sort-intersection-types rule

---

docs/components/Html.astro

Fixes issue where browsers try to translate https://perfectionist.dev/ from English -> English due to HTML lang being set to ru

fix(docs): change html lang to English

---

vite.config.ts

Manually changes the export from an ESM-style `export default` to a CJS-style `export =`. This better describes `dist/index.js`'s `module.exports = index`.
Fixes #177.
You can test this out locally by either:
* Replacing `node_modules/eslint-plugin-perfectionist/dist/index.d.ts` in https://github.com/JoshuaKGoldberg/repros/tree/repro-eslint-plugin-perfectionist-default-export-types
* Running `npx @arethetypeswrong/cli --pack` on the repo
Before this change, attw's `"eslint-plugin-perfectionist"` report was:
```plaintext
node10: ❗️ Incorrect default export
node16 (from CJS): ❗️ Incorrect default export
node16 (from ESM): 🐛 Used fallback condition
🎭 Masquerading as CJS
bundler: 🐛 Used fallback condition
```
Now:
```plaintext
node10: 🟢 
node16 (from CJS): 🟢 (CJS)
node16 (from ESM): 🐛 Used …
```

fix: switch `export default` to `export =` in `dist/index.d.ts`

---

rules/sort-classes.ts
test/sort-classes.test.ts

I believe that the `modifiers` and `selectors` priority order for `sort-classes` is intuitive enough to do what users expect the rule to do in cases where an element matches multiple user-entered groups. However, giving the matched group's name in the ESLint error message would still be a good idea. This can help users in debugging their configuration, especially complex ones involving custom groups.
New error added: `unexpectedClassesGroupOrder`. This error will show the element's respective group they matched.
_Note_:  Elements that do not belong in the same group but end up being regrouped together by the user's configuration will not throw an `unexpectedClassesGroupOrder` error, but a usual `unexpectedClassOrder` instead.
Configuration: 
```json
"perfectionist/sort-classes": ["error", …
```

`sort-classes` Add the element's matched group in ESlint error messages

---

docs/content/guide/getting-started.mdx
rules/sort-array-includes.ts
rules/sort-astro-attributes.ts
rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-svelte-attributes.ts
rules/sort-switch-case.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
rules/sort-vue-attributes.ts
test/sort-objects.test.ts
utils/complete.ts
utils/get-settings.ts

Cross-rule settings. Example:
```js
import perfectionist from 'eslint-plugin-perfectionist'
export default [
{
plugins: {
perfectionist,
},
rules: {
'perfectionist/sort-objects': ['error', {
type: 'alphabetical',
}],
'perfectionist/sort-interfaces': ['error'],
},
settings: {
perfectionist: {
type: 'line-length',
partitionByComment: true,
},
},
},
]
```
#202
---

feat: allow specifying cross-rule settings

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
test/sort-classes.test.ts

Solves https://github.com/azat-io/eslint-plugin-perfectionist/issues/189.
- Adds a new `selector`: `property-function`, with a higher priority than `property`. This selector will only match properties whose **values** are **directly** functions or arrow-functions (directly meaning that assigning a property a literal referring to a function will not detect it as a `property-function`). Properties **typed** as a function but without values will not be recognized as `property-function`.
I have been wondering if this feature should be implemented as a custom-group feature instead. (c.f: https://github.com/azat-io/eslint-plugin-perfectionist/issues/189#issuecomment-2276853937)
I agree with @OlivierZal that this is probably worth adding as an official group.

Allow `sort-classes` to match `property-function`: properties whose values are directly functions or arrow-functions.

---

rules/sort-classes.ts

As mentioned by @OlivierZal, the current way of checking if a class member is `#private` is done by analyzing its first character. This PR replaces this check with official ESLint typings.

feat: `sort-classes`: improved checks done to identify if a member is #private

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
test/sort-classes.test.ts

Fixes #207.
This PR adds the following:
- A new behavior for the `unknown` group: If the `unknown` group is not referenced in the user's configuration, elements from the `unknown` group will be ignored and not sorted. This prevents `unknown` elements from being put and sorted at the bottom of the class.
I have chosen not to add the `ignoreGroups` option as I believe this can be added in https://github.com/azat-io/eslint-plugin-perfectionist/pull/208 instead. This feature can be added later if needed anyway.
Example configuration that prevents `method` from being sorted:
```
"perfectionist/sort-classes": ["error", {
"groups": [
// Groups that do not include `method` nor `unknown`
]
}
]
```

feat: `sort-classes`: #207: Do not sort `unknown` elements if `unknown` is not referenced in `groups`

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
test/sort-classes.test.ts

Alternative PR to https://github.com/azat-io/eslint-plugin-perfectionist/pull/216, fixes #197 in a different way than the original idea.
The `optional` modifier has a lower priority than accessibility modifiers `public`, `protected` and `private`, meaning that
`a?` gets recognized as a `public-property` before `optional-property`.
Note that these PRs do not solve the exact same cases:
- This PR allows users to place optional members in a different group than the required ones while #216 only sorts optional and required members from the same group.
- This PR does not allow users to put `property` and `method` in the same group while putting optional members from both groups at the top (or at the bottom). #216 allows it.

feat: `sort-classes`: #197: Adds `optional` modifier to `property` and `method`

---

rules/sort-switch-case.ts
test/sort-switch-case.test.ts

fix: `sort-switch-case`: #229: case 'default': is confounded with default: clause

---

rules/sort-enums.ts
test/sort-enums.test.ts

Fixes #226.
Will not sort
```ts
enum Enum {
B = 'B',
A = Enum.B,
}
```
```ts
enum Enum {
B = 'B',
A = B,
}
```
```ts
enum Enum {
A = 0,
C = 1,
B = A | Enum.C
}
```
but will sort
```ts
enum Enum {
B = 'B',
A = AnotherEnum.B,
}
```

fix: `sort-enums`: #226: enum sorting now takes into account dependencies

---

vite.config.ts

This PR forces code coverage to be at 100% for the `test:unit` check to succeed.

feat: Make `test:unit` check fail if code coverage is not 100%

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
test/sort-classes.test.ts

Bandaid fix for #234.
This PR places `static-block` right after `static-property` in default options. 
Ideally, we should determine if the `static` section depends on some of the class's static properties and sort them accordingly as well, see #239.

fix: `sort-classes`: #234: Place `static-block` after `static-property` in default groups.

---

docs/content/rules/sort-classes.mdx
rules/sort-classes-utils.ts
rules/sort-classes.ts
rules/sort-classes.types.ts
test/sort-classes.test.ts

Fixes https://github.com/azat-io/eslint-plugin-perfectionist/issues/201
Typings for this rule have been moved in their own file `sort-classes.types.ts`.
Improves the `customGroups` API by allowing an array of `CustomGroup` to be entered rather than an object. Entering an object will still use the currently existing `customGroups` API.
A `CustomGroup` may be one of the following:
```ts
interface SingleCustomGroup {
groupName: string
type?: 'alphabetical' | 'natural' | 'line-length' | 'unsorted'
order?: 'asc' | 'desc'
selector?: string
modifiers?: string[]
elementNamePattern?: string
decoratorNamePattern?: string
}
```
or 
```ts
interface CustomGroupBlock {
groupName: string
type?: 'alphabetical' | 'natural' | 'line-length' | 'unsorted'
order?: 'asc' | 'desc'
anyOf: Array<{
selector?: …
```

feat: `sort-classes`: #201: Improved and extensible custom groups

---

package.json
pnpm-lock.yaml

When installing on Node 18, installation can fail with “Not compatible with your version of node/npm”. This is because one of the dependencies, minimatch 10, [requires Node 20](https://github.com/isaacs/minimatch/blob/0569cd3373408f9d701d3aab187b3f43a24a0db7/package.json#L53), whereas our current version of eslint-plugin-perfectionist [supports Node 18](https://github.com/azat-io/eslint-plugin-perfectionist/blob/0c724e0025ddbcb62eb082ae6c1fe3a7a01815de/package.json#L33).
> npm error code EBADENGINE
> npm error engine Unsupported engine
> npm error engine Not compatible with your version of node/npm: minimatch@10.0.1
This PR downgrades minimatch at no cost, as there were no meaningful changes between 9 and 10 ([changelog](https://github.com/isaacs/minimatch/blob/0569cd3373408f9d701d3aab187b …

Can’t install with engineStrict=true on Node 18

---

rules/sort-astro-attributes.ts
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-jsx-props.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-svelte-attributes.ts
rules/sort-union-types.ts
rules/sort-vue-attributes.ts
test/sort-astro-attributes.test.ts
test/sort-imports.test.ts
test/sort-interfaces.test.ts
test/sort-intersection-types.test.ts
test/sort-jsx-props.test.ts
test/sort-object-types.test.ts
test/sort-objects.test.ts
test/sort-svelte-attributes.test.ts
test/sort-union-types.test.ts
test/sort-vue-attributes.test.ts
test/validate-groups-configuration.test.ts
utils/validate-groups-configuration.ts

Resolves (partially) #214. The `sort-classes` rule is not part of this PR as checking if a group entered by the user is part of predefined groups requires a more complex strategy which I believe deserves its own PR.
Checks and validates group configuration for rules using `groups`. Configurations referencing groups that are
- not part of predefined groups
- and not defined in `customGroups`
are very likely user mistakes or typos. These groups are considered invalid and will throw an error, stopping ESLint.
Affected rules:
- `sort-astro-attributes`
- `sort-imports`
- `sort-interfaces`
- `sort-intersection-types`
- `sort-jsx-props`
- `sort-object-types`
- `sort-object`
- `sort-svelte-attributes`
- `sort-union-types`
- `sort-vue-attributes`
Remaining to do:
- Some tests have been slightly …

feat: all rules: #214: Warn the user/Throw an error when a group entered in config does not exist

---

docs/content/rules/sort-sets.mdx
index.ts
rules/sort-array-includes.ts
rules/sort-sets.ts
test/sort-sets.test.ts

This PR adds a new rule: `sort-sets`. This rule directly uses the `sort-array-includes`'s rule code, so its options are the same.
However, it doesn't verify that the `has` method is directly called afterward. The only side effect I can think of from sorting a set is that because the iteration order of `Set` is the insertion order, code that depends on this may get affected, but the `sort-map` rule has the same side effect and doesn't seem to take this into account either.

feat: `sort-sets`: New rule

---

rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-objects.ts
rules/sort-variable-declarations.ts
test/sort-classes.test.ts
test/sort-enums.test.ts
test/sort-objects.test.ts
test/sort-variable-declarations.test.ts
typings/index.ts
utils/compare.ts
utils/sort-nodes-by-dependencies.ts

Fixes #234.
Fixes #237.
Fixes #238.
Fixes #240.
Fixes #241.
Fixes #242.
Fixes #243.
Fixes #244.
Fixes #245.
Fixes #248.
Fixes #249.
Fixes #250.
This PR fixes various issues related to dependency detection.
`static` block's body dependencies will now be taken into account.
Static properties referenced with the class's name keyword will now be detected as dependencies.
I have chosen to consider that function property's body, just like method's body, should not be affected by dependencies, because they don't depend on their order to compile or run correctly.
This means that the `works with body dependencies` tests become irrelevant.
These tests were not working as expected in the first place:
_Example 1_ (code considered valid)
https://github.com/azat-io/eslint-plugin-perfectionist/blob/305d8 …

fix: `sort-classes` #234, #237, #238, #240, #241, #242, #243, #244, #245, #248, #249 and #250: Dependency related issues

---

rules/sort-classes.ts
test/sort-classes.test.ts

fix: `sort-classes` #257: Template literal expressions are not detected as dependencies

---

rules/sort-variable-declarations.ts
test/sort-classes.test.ts
test/sort-variable-declarations.test.ts

This PR fixes dependency related issues within the `sort-variable-declarations` rule.
It also adds a couple related additional unit tests in `sort-classes`.
Fixes #254.
Fixes #256.
```
let b = {x: 1},
a = b.x;
```
```
let b = 1,
a = !b;
```
```
let b = {x: 1},
a = b?.x;
```
```
let b = 1,
a = b!;
```
```
let b = 1,
a = b as any;
```
```
let b = 1,
a = <any>b;
```
```
let b = 1,
a = b ? 0 : 1;
```
```
let b = '',
a = `${b}`
```
```
let b = {x: 1},
a = {...b}
```

fix: `sort-variable-declarations` #254 and #256: dependencies related issues

---

rules/sort-astro-attributes.ts
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-jsx-props.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-svelte-attributes.ts
rules/sort-union-types.ts
rules/sort-vue-attributes.ts
test/sort-astro-attributes.test.ts
test/sort-imports.test.ts
test/sort-interfaces.test.ts
test/sort-intersection-types.test.ts
test/sort-jsx-props.test.ts
test/sort-object-types.test.ts
test/sort-objects.test.ts
test/sort-svelte-attributes.test.ts
test/sort-union-types.test.ts
test/sort-vue-attributes.test.ts

This PR extends #204 to other rules using groups: Comparisons between members that do not belong in the same group will have a more detailed error message, allowing the user to know which element belong to which group.
Affected rules:

feat: all rules: Add the element's matched group in ESlint error messages

---

rules/sort-objects.ts
rules/sort-variable-declarations.ts
test/sort-objects.test.ts

Fixes #262.
The dependency detection used is the same as the one used for `sort-variables-declarations`.
Furthermore, function bodies used to be taken into account for dependencies, which is not required for code to be able to compile and run correctly, so this has been removed.

feat: `sort-objects`: Missing dependency detections

---

rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-objects.ts
rules/sort-variable-declarations.ts
test/sort-classes.test.ts
test/sort-enums.test.ts
test/sort-objects.test.ts
test/sort-variable-declarations.test.ts
utils/sort-nodes-by-dependencies.ts

Resolves #270.
Adds a new error for each rule that is impacted by dependency order:
Code 
```ts
class Class {
a = { // A very complex object depending on `static z`
// ...
attribute: Class.z,
// ...
}
// [...] Many other members
someMethod() {
// ...
}
static z = 0
}
```

feat(multiple-rules): #270: add `dependencyOrder` errors

---

rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-objects.ts
test/sort-classes.test.ts
test/sort-enums.test.ts
test/sort-objects.test.ts

Fixes #275 for `sort-classes`, `sort-objects` and `sort-enums`.
The problem comes from the fact that the dependency check is done within each "block" partitioned by comments/line, rather than globally across the whole class/object/enum.
There is very little code change in reality! A large code block has been moved out of a `for` block; so the new indent generates a lot of line changes.
Note: the following code
```ts
class Class {
b = this.a
// Part1
a
}
```
Will get sorted into
```ts
class Class {
a
// Part1
b = this.a
}
```
This means that `b` is now part of the partitioned group defined by `Part1`! Ideally, we would want to get
```ts
class Class {
a
b = this.a
// Part1
}
```
or
```ts
class Class {
// Part1
a
b = this.a
}
```
Unfortunately, the current sorting implementation permutates …

fix(sort-classes): #275: partitionByComment/partitionByLine takes precedence over dependencies

---

docs/content/rules/sort-exports.mdx
rules/sort-exports.ts
test/sort-exports.test.ts

Resolves #277 .
This PR adds the `partitionByComment` option to `sort-exports`. This rule already has `partitionByNewLine`.

feat(sort-exports): #277: Add partitionByComment option

---

docs/content/rules/sort-intersection-types.mdx
rules/sort-intersection-types.ts
test/sort-intersection-types.test.ts

Adds these two options to `sort-intersection-types`.
It is important to write
```ts
type Type =
D &
A &
C &
E &
B
```
and not 
```ts
type Type =
D
& A 
& C 
& E 
& B
```

feat(sort-intersection-types): Adds `partitionByComment` and `partitionByNewLine`

---

docs/content/rules/sort-union-types.mdx
rules/sort-union-types.ts
test/sort-union-types.test.ts

Adds these two options to `sort-union-types`.
It is important to write
```ts
type Type =
D |
A |
C |
E |
B
```
and not 
```ts
type Type =
D
| A 
| C 
| E 
| B
```

feat(sort-union-types): Adds `partitionByComment` and `partitionByNewLine`

---

docs/content/rules/sort-named-imports.mdx
rules/sort-named-imports.ts
test/sort-named-imports.test.ts

Adds these two options to `sort-array-includes` and `sort-sets`.

feat(sort-named-imports): Adds `partitionByComment` and `partitionByNewLine`

---

docs/content/rules/sort-named-exports.mdx
rules/sort-named-exports.ts
test/sort-named-exports.test.ts

Adds these two options to `sort-named-exports`.

feat(sort-named-exports): Adds `partitionByComment` and `partitionByNewLine`

---

docs/content/rules/sort-maps.mdx
rules/sort-maps.ts
test/sort-maps.test.ts

Adds these two options to `sort-maps`.

feat(sort maps): Adds `partitionByNewLine` and `partitionByComment`

---

docs/content/rules/sort-variable-declarations.mdx
rules/sort-variable-declarations.ts
test/sort-variable-declarations.test.ts

Adds these two options to `sort-variable-declarations`.

feat(sort-variable-declarations): Adds `partitionByComment` and `partitionByNewLine`

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-sets.mdx
rules/sort-array-includes.ts
test/sort-array-includes.test.ts
test/sort-sets.test.ts

Adds these two options to `sort-array-includes` and `sort-sets`.

feat(sort-array-includes + sort-sets): Adds `partitionByComment` and `partitionByNewLine`

---

rules/sort-astro-attributes.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-jsx-props.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-svelte-attributes.ts
rules/sort-union-types.ts
rules/sort-vue-attributes.ts
utils/sort-nodes-by-groups.ts

All rules handling groups (with the exception of `sort-classes` with a new CustomGroup API) do the same thing when it comes to sorting nodes by groups. This PR refactor codes to reduce code duplication for those rules.

refactor(multiple-rules): adds `sort-nodes-by-groups` function to reduce code duplication

---

docs/content/rules/sort-object-types.mdx
rules/sort-object-types.ts
test/sort-object-types.test.ts

Adds this option to `sort-object-types`.

feat(sort-objects-types): adds `partitionByComment`

---

docs/content/rules/sort-enums.mdx
rules/sort-enums.ts
test/sort-enums.test.ts

Adds this option to `sort-enums`.
No test was changed, `${ruleName}:` was added in places where it was missing and re-indented some lines.

feat(sort-enums): adds `partitionByNewLine`

---

test/sort-intersection-types.test.ts
test/sort-union-types.test.ts
utils/compare.ts

Resolves #181 .
Today with the `alphabetical` or `natural` sort, the following code is valid
```ts
type T =
{ a: string } &
{ b: string }
```
but this one is not:
```ts
type T =
{ a: string } &
{  b: string }
```
The issue lies in the fact that `{  b` is "lower" than `{ a` because of the whitespace before `b`.
Giving the possibility for users to ignore whitespaces can solve this issue.  
This PR changes the following:

fix(all-rules): Ignores whitespaces in node names

---

rules/sort-classes.ts
test/sort-classes.test.ts

Fixes #268.
When implementing the notion of ignored `unknown` group, ignored nodes were set to avoid creating linting errors: it's a bit counter-intuitive to tell the user that an ignored node should be before or after another node if it's supposed to be ignored.
Because linting errors are based on adjacent nodes comparison, classes that **only** have errors between ignored nodes and their adjacent nodes will not raise any error, and thus not trigger linting.
In practice, this likely shouldn't happen often and is fixed as soon as another error is detected in the class, as it will trigger linting and correctly sort it, so I don't believe this is a big issue (I detected it by accident while trying something else).
Custom groups with the `unsorted` sort type are unrelated to this issue. Only …

fix(sort-classes): #268: ignored nodes prevent their adjacent node from triggering linting

---

rules/sort-classes.ts
test/sort-classes.test.ts

Fixes #300 .
Fixes possible runtime errors due to function body dependencies not being considered when passing callback functions in property assignments. Issue possibly affects `static` block as well in some cases. One test affected had to be updated.

fix(sort-classes): fixes runtime error related to dependencies

---

docs/content/rules/sort-classes.mdx
rules/sort-classes-utils.ts
rules/sort-classes.ts
rules/sort-classes.types.ts
test/sort-classes.test.ts

Resolves #298 
Adds a `elementValuePattern` option for custom groups, allowing users to match **non-function property** values.

feat(sort-classes): adds `elementValuePattern` filter for properties

---

rules/sort-classes-utils.ts
rules/sort-classes.ts
test/sort-classes-utils.test.ts
test/validate-groups-configuration.test.ts
utils/validate-groups-configuration.ts

Continuation of https://github.com/azat-io/eslint-plugin-perfectionist/pull/232 to solve https://github.com/azat-io/eslint-plugin-perfectionist/issues/214.
Groups that are not part of predefined groups nor entered as custom groups have no reason to exist in the groups attribute. `sort-classes` was the only remaining rule not to have this feature, because predefined groups are computed differently.

feat(sort-classes): Throw an error when a group entered in config does not exist/is duplicated

---

docs/content/guide/getting-started.mdx
test/get-settings.test.ts
utils/get-settings.ts

- Adds `specialCharacters` and `matcher` to global settings, as all rules allow them.
- Adds tests and ensure 100% coverage.
- Improves the error in case of invalid settings: displays the invalid settings provided.
- Updates docs.

feat: add `specialCharacters` and `matcher` to settings

---

rules/sort-classes.ts
rules/sort-imports.ts
test/clean-groups-option.test.ts
test/sort-imports.test.ts
utils/clean-groups-option.ts
utils/get-options-with-clean-groups.ts
utils/sort-nodes-by-groups.ts

Fixes #311
Fixes #315 
Fixes #316
Most of the new lines added come from tests. Some code had to be moved around, but there is not that much added code in the end, especially since the functions doing the heavy work already existed for other rules.
This PR fixes three related issues at the same time: some code was refactored to follow the same logic that the other rules use.
In the current code, side effect imports do not actually stay in place: when a side effect import is encountered, they are put at the end of the group they belong. If for that same group a non-side effect import is encountered, that group is sorted, making the previous step go to waste!
Sorting or not sorting side effects is actually a little bit more complex than it seems: it depends on the user's `groups` option, …

feat(sort-imports): Improves side-effect handling behavior

---

rules/sort-switch-case.ts
test/sort-switch-case.test.ts

Fixes #326 
This PR makes sure that `switch(true)` is still disabled, but enables other expressions to be entered.

fix(sort-switch-case): fixes expressions being ignored

---

docs/content/rules/sort-objects.mdx
rules/sort-objects.ts
test/sort-objects.test.ts

`sort-interfaces` and `sort-object-types` both handle the `multiline` and `method` groups.
This PR allows `sort-objects` to handle them as well.
Handles 3 syntaxes:
- `myFunc: () => {}`,
- `myFunc: function() {}`,
- `myFunc() {}`,
Removes unused `Position` enum.

feat(sort-objects): adds multiline and method groups

---

docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-intersection-types.mdx
docs/content/rules/sort-object-types.mdx
docs/content/rules/sort-objects.mdx
docs/content/rules/sort-union-types.mdx
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-union-types.ts
test/sort-imports.test.ts
test/sort-interfaces.test.ts
test/sort-intersection-types.test.ts
test/sort-object-types.test.ts
test/sort-objects.test.ts
test/sort-union-types.test.ts
test/validate-newlines-and-partition-configuration.test.ts
utils/get-newlines-errors.ts
utils/make-newlines-fixes.ts
utils/sort-nodes-by-dependencies.ts
utils/validate-newlines-and-partition-configuration.ts

Resolves #146
Fixes #329
This PR aims to extend the `newlinesBetween` option of `sort-imports` to other rules.
Affected rules:
`partitionByNewLine` and `newlinesBetween` are incompatible:
Only one option at a time can be active.
An error if thrown otherwise: `The 'partitionByNewLine' and 'newlinesBetween' options cannot be used together`

feat(multiple-rules): adds `newlinesBetween`

---

docs/content/rules/sort-heritage-clauses.mdx
index.ts
readme.md
rules/sort-heritage-clauses.ts
test/sort-heritage-clauses.test.ts

This PR adds a `sort-heritage-clauses` (feel free to suggest another name if you find a better one) that allows users to sort classes `implements` and interfaces `extends` clauses.
Example:
```ts
interface Interface extends Loggable, Pausable, Startable {
// ...
}
```
```ts
class Class implements Loggable, Pausable, Startable {
// ...
}
```
```ts
{
customGroups: { [key in T[number]]: string[] | string }
type: 'alphabetical' | 'line-length' | 'natural'
specialCharacters: 'remove' | 'trim' | 'keep'
groups: (Group<T>[] | Group<T>)[]
matcher: 'minimatch' | 'regex'
order: 'desc' | 'asc'
ignoreCase: boolean
}
```
There is only one predefined group: `unknown`.
I don't believe that `partitionByNewline` and `partitionByComment` have relevant use cases here.

feat: new rule: `sort-heritage-clauses`

---

docs/content/rules/sort-classes.mdx
rules/sort-classes-utils.ts
rules/sort-classes.ts
rules/sort-classes.types.ts
test/sort-classes-utils.test.ts
test/sort-classes.test.ts

`sort-classes`'s `customGroups` option currently supports:
- an object (old API): like other rules, each key is the group's name, and its value the pattern to match the value of the class's member.
- an array (new API) with more options.
Migrating from the old to the new API is very straightforward.
Old API:
```ts
{
"key1": "value1",
"key2": "value2"
}
```
New API:
```ts
[
{
"groupName": "key1",
"elementNamePattern": "value1"
},
{
"groupName": "key2",
"elementNamePattern": "value2"
}
]
```
This PR removes support for the old API and the code associated and adds a section to the documentation to help users who have not yet switched to the new API to migrate.

feat(sort-classes)!: removes support for old `customGroups` API

---

rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-decorators.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-heritage-clauses.ts
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-sets.ts
rules/sort-switch-case.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
utils/common-json-schemas.ts
utils/complete.ts

This PR reduces code duplication in 2 ways:
- Each rule has duplicated `defaultOptions`. Creates a single constant for that per rule.
- All rules share some similar JSON schemas, for `type`, `order`, etc. Put these in common in a `utils/common-json-schemas.ts` file.
Here is the list of JSON schemas attributes put in common:
- `type`
- `order`
- `matcher`
- `ignoreCase`
- `specialCharacters`
- `groups`
- `customGroups` (Object-based API)
- `partitionByComment`
No other code logic or tests have been touched.
- Makes `complete` return a new object rather than using `Object.assign`.

refactor: reduce JSON schema and options duplication

---

rules/sort-switch-case.ts
test/sort-switch-case.test.ts
utils/get-comment-after.ts
utils/make-comment-after-fixes.ts
utils/make-fixes.ts

Fixes #335.
Fixes #343.
This PR refactors and improves `sort-switch-case` to
- Use `makeFixes` and the new `makeAfterCommentFixes` as much as possible, which handles comments (for #335 and #343).
- Enable users to sort switch statements with cases that do **not** break/return.
There are **3** sorting phases. Phases **1** and **2** fixes are done in the same ESLint cycle. Phase **3** errors are shown, but fixes are done in another cycle once all phase 1 and 2 errors are fixed (this is invisible to the user).
A group is a list of consecutive case statements that can safely be re-ordered within that group. 
Order them using `makeFixes` which properly handles comments.
This is not done in Phase 1 due to the differences between `case` nodes and `default` nodes AST-parser wise. This doesn't use …

feat(sort-switch-case): Improvements

---

index.ts

Currently there are problems with types, because TypeScript ESLint types are not exactly identical to ESLint types. This pull request fixes that, but it does it in a slightly non-natural way.
```ts
// eslint.config.ts
import type { Linter } from "eslint";
import perfectionist from "eslint-plugin-perfectionist";
export default [
perfectionist.configs['recommended-line-length'],
] satisfies Linter.Config[];
```
#338
---

fix: make types compatible with eslint types

---

docs/content/rules/sort-switch-case.mdx
rules/sort-switch-case.ts
test/sort-switch-case.test.ts

Fixes #348
Despite being wrapped in `{ }`, block case statements need `break`.
- Fixes `break` and `return` not being considered necessary for block case statements. This means that block statements without `break/return` might still get sorted when they should not. 1 test duplicated 3 times had to be updated (commit 1: 15e07e3ef82dfe43425f1d713e7cf5370a05861b)
- Fixes an issue with the new feature, allowing sorting nodes that don't have break/return: if the **last** node has no `break/return`: the whole cases group associated must stay in place. 
- Fixes #348.

fix(sort-switch-case): fixes block case statements ignoring break/return

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
rules/sort-classes.types.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-maps.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
test/sort-classes.test.ts
utils/common-json-schemas.ts

The majority of lines added are tests and documentation.
Simply adds those two options to `sort-classes`.
- Adds `partitionByNewLine` option. `partitionByComment` already exists and probably is a better use case, but supporting `partitionByNewline` is a matter of a couple of lines. Might as well add it!
- Adds `newlinesBetween` option (requested here: https://github.com/azat-io/eslint-plugin-perfectionist/issues/350#issuecomment-2453047795)
- Creates a `partitionByNewLineJsonSchema` JSON schema to reduce code duplication.
As with other rules using this option, `partitionByNewLine` and `newlinesBetween` can not be used together.

feat(sort-classes): adds `partitionByNewLine` and `newlinesBetween` options

---

rules/sort-classes.ts
test/sort-classes.test.ts

Fixes #355
Hash private properties (`#a` for example) were not detected as dependencies. 
- Fixes the bug and adds tests.
- Also removes some duplicate code.

fix(sort-classes): fix # properties not being detected as dependencies

---

rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-interfaces.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-variable-declarations.ts
test/sort-classes.test.ts
test/sort-interfaces.test.ts
test/sort-maps.test.ts
test/sort-named-exports.test.ts
utils/pairwise.ts

**⚠️ Hide whitespace changes to view actual changes!**
Pretty much all the code change comes from indentation that was reduced.
I initially put this commit in #358 but thought it would be best to put it in a separate PR. Even if there are little actual changes, GitHub displays a lot of line changes.
This PR simply transforms long 
```ts
if (a) {
if (b) {
...
}
}
```
blocks into
```ts
if (!a) {
return
}
if (!b) {
return
}
```
This makes code more readable by greatly reducing indentation.
No test modified, no test removed. A couple of trivial tests were added for coverage purpose.

refactor: reduce amount of nested statements

---

docs/content/rules/sort-imports.mdx
rules/sort-imports.ts
test/get-typescript-import.test.ts
test/read-closest-ts-config-by-path.test.ts
test/sort-imports.test.ts
utils/get-typescript-import.ts
utils/read-closest-ts-config-by-path.ts

Resolves #317
Adds a `tsconfigRootDir?: string` option (can be changed if needed). When passed by the user, each time a file is linted, the nearest `tsconfig.json` file will be searched, read, and used to determine if an import is internal or not.
Will try to dynamically load (and cache) `typescript` so this should not impact non-typescript users.
The `tsconfig.json` search and cache algorithm was taken from https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts 🙏. 
- Linting is run for a given file.
- Check if `tsconfigRootDir` is entered. If not, sort as usual.
- Ensures that `typescript` is present. If not, sort as usual.
- If it is, search and read the closest `tsconfig.json` file and get the compiler …

feat(sort-imports): resolve aliased imports through tsconfig.json

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
rules/sort-classes.types.ts
test/sort-classes.test.ts

Resolves #350
In `sort-classes`, dependencies are detected and placed above class members that depend on them when needed. This process is required to ensure that compilation and runtime behavior is preserved.
There is one case where this process can feel overly cautious for users: when examining callback functions.
```ts
function someFunction(fn: () => any) {
return fn()
}
class Class {
a = someFunction(() => {
return this.b
})
b = 1
};
console.log(new Class().a) // prints undefined
``` 
In this example, we detect that `b` should be before `a` (good).
Some front-end frameworks (`Vue` or `Angular` to only name a few) offer reactive features, such as [Signals](https://angular.dev/guide/signals) or [Computed properties](https://vuejs.org/guide/essentials/computed.html) which rely on …

feat(sort-classes): adds `ignoreCallbackDependenciesPatterns` option

---

test/sort-switch-case.test.ts

Issue #368 is already fixed in `next`, but this PR adds a dedicated unit test.

test(sort-switch-case): adds unit test for #368

---

rules/sort-imports.ts
test/sort-imports.test.ts

Support optional chaining imports:
```js
import styles from './styles.scss?module'
```
N/A.
---

fix(sort-imports): support optional chaining imports

---

rules/sort-classes.ts
test/sort-classes.test.ts

`declare class` methods act like `abstract` methods and can't have an implementation. As such, they need a safety semicolon when declared inline.
```ts
declare class Class {
b(); a()
}
```
gets sorted to
```ts
declare class Class {
a() b();
}
```
instead of
```ts
declare class Class {
a(); b();
}
```
This PR fixes this.
- Fixes the bug (one line fix).
- Adds a unit test.

fix(sort-classes): adds missing safety semicolon for `declare class` inline methods

---

rules/sort-imports.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts

Replaces 
```ts
import { isSortable } from 'utils/is-sortable'
```
Occurrences with
```ts
import { isSortable } from '../utils/is-sortable'
```
to prevent runtime errors.

fix: fixes invalid `isSortable` import

---

docs/content/rules/sort-classes.mdx
rules/sort-classes.ts
rules/sort-classes.types.ts
test/sort-classes.test.ts

`sort-modules` introduced a new modifier: `async`. As requested [here](https://github.com/azat-io/eslint-plugin-perfectionist/pull/360#discussion_r1843026872), this PR adds the `async` modifier in `sort-classes` as well for the `method` and `function-property` selectors.
The `async` modifier has the lowest priority out of all modifiers.
No test impacted, I just improved an existing test and added new ones.

feat(sort-classes): adds `async` modifier

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-classes.mdx
docs/content/rules/sort-decorators.mdx
docs/content/rules/sort-enums.mdx
docs/content/rules/sort-exports.mdx
docs/content/rules/sort-heritage-clauses.mdx
docs/content/rules/sort-imports.mdx
docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-intersection-types.mdx
docs/content/rules/sort-jsx-props.mdx
docs/content/rules/sort-maps.mdx
docs/content/rules/sort-modules.mdx
docs/content/rules/sort-named-exports.mdx
docs/content/rules/sort-named-imports.mdx
docs/content/rules/sort-object-types.mdx
docs/content/rules/sort-objects.mdx
docs/content/rules/sort-sets.mdx
docs/content/rules/sort-switch-case.mdx
docs/content/rules/sort-union-types.mdx
docs/content/rules/sort-variable-declarations.mdx
package.json
pnpm-lock.yaml
test/sort-imports.test.ts
test/sort-object-types.test.ts
test/sort-union-types.test.ts
test/sort-variable-declarations.test.ts
utils/compare.ts

Hi. This is probably the last breaking change in the upcoming release. But I'm not entirely sure we need it. I'd like to discuss it.
This pull request changes the current library for natural sorting from  [natural-compare-lite](https://github.com/litejs/natural-compare-lite) to [natural-orderby](https://github.com/yobacca/natural-orderby).
- **Supported Library**. The last release of the library we are currently using was 9 years ago. We can't influence its development in any way, we can't inform the author of the library about any problems. At the same time, the last release of the new library was today.
- **Support numeric separators**. The old library came out quite a long time ago and therefore did not support numeric separators (`1_000_000`). The new library started to support this …

feat!: move from natural-compare-lite to natural-orderby

---

package.json
pnpm-lock.yaml

Fixes #378
Moves `@azat-io/eslint-config` from `dependencies` to `devDependencies`.

fix: fixes peer dependencies issues

---

rules/sort-modules.ts
test/sort-modules.test.ts

Will fix temporarily #376 
The actual fix requires computing and detecting decorators similarly to how comments are detected, but it's not straightforward.
In the meantime, we can simply ignore `export decorated classes`.
- 2 tests commented: sorting is disabled in those cases.
- 1 test added.

fix(sort-modules): disables sorting for `export decorated` classes

---

rules/sort-decorators.ts
rules/sort-heritage-clauses.ts
rules/sort-modules.ts
test/sort-array-includes.test.ts
test/sort-classes.test.ts
test/sort-decorators.test.ts
test/sort-exports.test.ts
test/sort-heritage-clauses.test.ts
test/sort-imports.test.ts
test/sort-maps.test.ts
test/sort-modules.test.ts
test/sort-named-exports.test.ts
test/sort-named-imports.test.ts
test/sort-objects.test.ts
test/sort-sets.test.ts
test/sort-switch-case.test.ts
test/sort-variable-declarations.test.ts
utils/get-node-decorators.ts

Some runtime errors happen in projects that do not user `typescript-eslint` parser.
For example, decorators are not detected (and the `decorators` property will not exist on nodes, even though `typescript-eslint` types will say it necessarily exists).
This PR fixes them and adds for each rule some basic tests to ensure that the rule works fine in a non-typescript environment, using `eslint`'s Rule Tester rather than `typescript-eslint`'s Rule Tester.

fix: fixes runtime errors in non typescript-eslint projects 

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-classes.mdx
docs/content/rules/sort-exports.mdx
docs/content/rules/sort-intersection-types.mdx
docs/content/rules/sort-maps.mdx
docs/content/rules/sort-modules.mdx
docs/content/rules/sort-named-exports.mdx
docs/content/rules/sort-named-imports.mdx
docs/content/rules/sort-object-types.mdx
docs/content/rules/sort-objects.mdx
docs/content/rules/sort-sets.mdx
docs/content/rules/sort-union-types.mdx
docs/content/rules/sort-variable-declarations.mdx

Small documentation fixes.
- Fixes invalid `enum` references.
- Fixes invalid example in `sort-modules` to follow the current default options.

docs: small fixes

---

docs/content/rules/sort-objects.mdx
rules/sort-objects.ts
test/sort-objects.test.ts

Resolves #392
- Deprecates the `destructureOnly` option in the documentation (still usable).
- Adds a `objectDeclarations: boolean` option (by default `true`): when false, will not sort object declarations. 
- Adds a `destructuredObjects: boolean | { groups: boolean }` option (by default `true`): when false, will not sort destructured objects. When `{ groups: false }`, will not use groups to sort destructured objects.
- Uses the same existing option name `groups`, making it clear that this sub-option is linked with the parent `groups` option.
- Gives flexibility later if users require specifying specific grouping for destructured objects: `{ groups: boolean }` can be extended to `{ groups: boolean | string[] | string[][] }`.

feat(sort-objects): adds `objectDeclarations ` and `destructuredObjects ` options

---

tsconfig.json

Reduces the potential of import errors by removing the `baseUrl: "."` option in `tsconfig.json`.
`import { pairwise } from 'utils/pairwise'` or similar imports will now raise errors.
I don't think there should be any side effect in this.

fix: removes `baseUrl` from `tsconfig.json`

---

rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-decorators.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-imports.ts
rules/sort-interfaces.ts
rules/sort-intersection-types.ts
rules/sort-maps.ts
rules/sort-modules.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
test/sort-decorators.test.ts
utils/get-comments-before.ts
utils/get-node-range.ts
utils/make-fixes.ts
utils/make-newlines-fixes.ts

Fixes #399.
Comment blocks above the first decorator are almost always meant not to be moved around.
Prevents the highest comment blocks(`/** */`) placed above the first decorator (and comments above that block) from being sorted.
Initially:
```ts
class Class {
// Should not move
/**
* JSDoc comment
*/
// B
@B()
/**
* A
*/
@A()
foo: number;
}
```
Result:
```ts
class Class {
// Should not move
/**
* JSDoc comment
*/
/**
* A
*/
@A()
// B
@B()
foo: number;
}
```
Non-block comments are not considered JSDoc comments and will not trigger this.
A test duplicated 3 times had to be updated. See 7c0d57161c7764df4e8b0e85d33b0f54952ead6b.

fix(sort-decorators): keeps JSDoc blocks in place

---

test/compare.test.ts
utils/compare.ts

Fixes #405.
One line fix.
The issue comes from the fact that the sort order is provided to the `natural-orderby` library, while an additional sort by order is done at the end, cancelling it.
https://github.com/azat-io/eslint-plugin-perfectionist/blob/eed1b809a954778baed8117abd72efcd39c9c0c8/utils/compare.ts#L60-L63
https://github.com/azat-io/eslint-plugin-perfectionist/blob/eed1b809a954778baed8117abd72efcd39c9c0c8/utils/compare.ts#L46
https://github.com/azat-io/eslint-plugin-perfectionist/blob/eed1b809a954778baed8117abd72efcd39c9c0c8/utils/compare.ts#L97
The PR also adds some simple additional unit tests for the `compare` function to prevent potential regressions in the future.

fix: fixes `natural` sort ignoring `order`

---

rules/sort-object-types.ts
test/sort-interfaces.test.ts
test/sort-object-types.test.ts
utils/is-node-function-type.ts

Fixes #409.
Allows union and intersection types resulting in functions to be detected, such as
```ts
(((v: false) => 'false') | ((v: true) => 'true')) & ((v: any) => any)
```

feat: improves function detection

---

docs/content/rules/sort-objects.mdx
rules/sort-objects.ts
test/get-matching-context-options.test.ts
test/sort-objects.test.ts
utils/common-json-schemas.ts
utils/get-matching-context-options.ts

Resolves #148.
Resolves #408.
Users have been requesting a way to have different sorting rules depending on context. For example:
- Sizes `xs`, `s`, `m`, `l`, `xl`.
- color: `r`, `g`, `b`.
While custom groups may solve this, having many contextual custom groups that are unrelated to each other makes the configuration hard to read and more prone to errors.
This PR proposes to use the native ESLint feature allowing users to enter multiple option configuration to solve the problem:
- Adds a `useConfigurationIf: { allNamesMatchPattern?: string }` (by default `{}`) to `sort-objects`.
If the `allNamesMatchPattern ` is provided by the user, the entered options configuration will be used if **all** the object's keys match the entered pattern.
- Detects color objects and sort them by `r`, `g`, …

feat(sort-objects): handles context-based configurations

---

rules/sort-object-types.ts
test/sort-interfaces.test.ts
test/sort-object-types.test.ts

Fixes #414
Similarly to call signatures, this PR prevents constructor signatures from being sorted together. 
```ts
interface Interface {
new (value: number | string): number;
new (value: number): unknown;
}
```
- Fixes the bug
- Adds tests for both `sort-interfaces` and `sort-object-types`.
- Renames a few tests.

fix(sort-interfaces): prevents constructor declarations from being sorted

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-object-types.mdx
docs/content/rules/sort-objects.mdx
docs/content/rules/sort-sets.mdx
rules/sort-array-includes-utils.ts
rules/sort-array-includes.ts
rules/sort-array-includes.types.ts
rules/sort-classes.types.ts
rules/sort-modules.types.ts
rules/sort-object-types.types.ts
rules/sort-sets.ts
test/sort-array-includes.test.ts
test/sort-sets.test.ts

Resolves #98
Adds the following features to `sort-array-includes` and `sort-sets`:
- `useConfigurationIf` feature (like `sort-objects`).
- `groups` and `customGroups`.
```ts
{
allNamesMatchPattern?: string
}
```
Default value: `[]`.
Allows to deprecate `groupKind` like in `sort-objects` (the option is still present and works just as before).
Selectors:
- `spread`: matches literal elements.
- `literal`: matches spread elements.
No modifiers.
Default value: `[]`.
Uses a similar array-based API as other rules.
- [adds newlines to improve readability](https://github.com/azat-io/eslint-plugin-perfectionist/pull/412/commits/bfd0765241653352f264abc7cfac07cd729ca163)
- [fixes invalid documentation](https://github.com/azat-io/eslint-plugin-perfectionist/pull/412/commits/d3e52f834dcfd725ae3b0aaaac97 …

feat(sort-array-includes): adds `useConfigurationIf` and `groups`

---

rules/sort-classes.types.ts
test/sort-classes.test.ts

It seems the current types for groups are pretty hard to read. I wrote a generic type to make types more readable. And added tests for types.
N/A.
---

refactor(sort-classes): make group types readable

---

rules/sort-classes.types.ts
rules/sort-modules.types.ts
rules/sort-object-types.types.ts
typings/index.ts
typings/join-with-dash.ts
typings/join.ts
typings/sorting-node.ts
typings/with-dash-suffix-or-empty.ts

- Extract the following types into their own files: `Join`, `SortingNode`.
- Transforms `Join` introduced in https://github.com/azat-io/eslint-plugin-perfectionist/pull/416  to `JoinWithDash` and uses it for other rules.

refactor: uses `Join` for other rules

---

rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-decorators.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-heritage-clauses.ts
rules/sort-imports.ts
rules/sort-intersection-types.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts
rules/sort-modules.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types-utils.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-switch-case.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
utils/create-node-index-map.ts
utils/is-partition-comment.ts
utils/pairwise.ts
utils/validate-groups-configuration.ts

Some micro-optimizations of the code.
**sort-array-includes:**
- Remove an unnecessary call `getNodeName` function.
- Move the `generatePredefinedGroups` function call outside the loop. Currently, this function is called at each iteration of the loop.
- Pre-group nodes by `groupKind` using `reduce`, reducing sorting complexity from O(n × k) to O(n).
- Replace repeated `indexOf` calls with a `Map` for node indices, reducing order-checking complexity from O(n²) to O(n).
**sort-classes:**
- Move the `generatePredefinedGroups` function call outside the loop. Currently, this function is called at each iteration of the loop.
**sort-decorators:**
- Replace repeated `indexOf` calls with a `Map` for node indices, reducing order-checking complexity from O(n²) to O(n).
**sort-enums:**
- Replace …

perf: improve rules performance

---

test/compare.test.ts
utils/compare.ts

Fixes the issue mentioned in this [comment](https://github.com/azat-io/eslint-plugin-perfectionist/issues/424#issuecomment-2557345446). 
Today, `custom` sort doesn't handle void (empty) characters well: `a` will not always come before `aa`.
`localeCompare`'s sorting behavior is to put `a` first, and in general to give the maximum priority to the `void` character. I think it's better to mimic this by default.
No, I think it's a **bug**: I believe users would expect the empty character to take maximum priority over any other character by default, like it is the case when locale-comparing strings, so this shouldn't be considered a breaking change.
- This is not easy:
- We require users to pass an `alphabet`: a list of unique ordered characters.
- Users can pass the alphabet as an array. In …

fix: `custom` sort type: give maximum priority to the `void` character

---

docs/content/rules/sort-classes.mdx
docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-modules.mdx
docs/content/rules/sort-object-types.mdx
rules/sort-classes/types.ts
rules/sort-imports.ts
rules/sort-modules/types.ts
rules/sort-object-types/types.ts
test/get-newlines-between-option.test.ts
test/rules/sort-classes.test.ts
test/rules/sort-imports.test.ts
test/rules/sort-interfaces.test.ts
test/rules/sort-modules.test.ts
test/rules/sort-object-types.test.ts
test/utils/get-newlines-between-option.test.ts
utils/common-json-schemas.ts
utils/get-newlines-between-option.ts
utils/get-newlines-errors.ts
utils/make-newlines-fixes.ts

First PR aiming to partially resolve the issue https://github.com/azat-io/eslint-plugin-perfectionist/issues/401.
- ⚙️ **PR 1 (this)**: Add `customGroup.newlinesInside` option. We will take the opportunity to create a `getNewlinesBetweenOption` method that will help us later to precisely customize newline behavior between two specific groups. 
- ❌ **PR 2**: Add a way to choose a specific newline behavior between two groups. See the proposals [here](https://github.com/azat-io/eslint-plugin-perfectionist/issues/401#issuecomment-2558581331).
We currently have the `newlinesBetween` option, which applies the same newlines-related rules between all groups.
This PR adds a sub-option for the new array-based `customGroups`:
- `newlinesInside?: 'always' | 'never'`
Here is the list of rules with …

feat: adds `customGroup.newlinesInside ` option

---

rules/sort-intersection-types.ts
rules/sort-union-types.ts

The differences between the source code of `sort-union-types` and `sort-intersection-types` are minimal (https://www.diffchecker.com/NZ9LSvo7/). Outside meta-related information (rule name, error IDs, etc), the only logic-related differences are
- When this rule is triggered (on union types vs on intersection types).
- Partition by comment: `tokenValueToIgnoreBefore`
https://github.com/azat-io/eslint-plugin-perfectionist/blob/0df348fd82ff2c409e6a09fde5e5d02bf291dfca/rules/sort-union-types.ts#L206
VS
https://github.com/azat-io/eslint-plugin-perfectionist/blob/0df348fd82ff2c409e6a09fde5e5d02bf291dfca/rules/sort-intersection-types.ts#L206
This PR creates a `sortUnionOrIntersectionTypes` function that puts all of this logic in common to greatly reduce code duplication.
No test impacted.

refactor: reduces duplication in `sort-union-types` and `sort-intersection-types`

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-imports.mdx
docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-jsx-props.mdx
docs/content/rules/sort-modules.mdx
docs/content/rules/sort-object-types.mdx
docs/content/rules/sort-objects.mdx
docs/content/rules/sort-sets.mdx
rules/sort-classes/types.ts
rules/sort-objects.ts
rules/sort-objects/does-custom-group-match.ts
rules/sort-objects/types.ts
test/rules/sort-objects.test.ts
utils/common-json-schemas.ts

Resolves #436
Adds the grouping system of `sort-object-types` to `sort-objects`, including the array-based `customGroups` option.
This is quite similar to what was done in #396.
Ordered from most to least important.
- methods: `method`, `member`.
- properties: `property`, `member`.
- `multiline`: This selector is deprecated: it allows users to keep using the `multiline` group, but the `multiline` modifier should be used instead (`multiline-member` group, for example).
`multiline`.
- `elementNamePattern`.
- `elementValuePattern` as requested [here](https://github.com/azat-io/eslint-plugin-perfectionist/issues/436#issuecomment-2571676945). Disabled for functions and arrow function values.

feat(sort-objects): adds array-based `customGroups` option

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-maps.mdx
rules/sort-maps.ts
rules/sort-maps/does-custom-group-match.ts
rules/sort-maps/types.ts
test/rules/sort-maps.test.ts

As usual, most lines added are tests and documentation 🙂
This PR adds the following features to `sort-maps`, to look very similar to `sort-array-includes`:
- `groups` option (no predefined group).
- `newlinesBetween` option.
- Array-based `customGroups`.
- `useConfigurationIf.allNamesMatchPattern`.

feat(sort-maps): adds `groups`, `customGroups` and `newlinesBetween`

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-classes.mdx
docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-intersection-types.mdx
docs/content/rules/sort-jsx-props.mdx
docs/content/rules/sort-modules.mdx
docs/content/rules/sort-object-types.mdx
docs/content/rules/sort-sets.mdx
docs/content/rules/sort-union-types.mdx
rules/sort-array-includes.ts
rules/sort-array-includes/types.ts
rules/sort-interfaces.ts
rules/sort-jsx-props.ts
rules/sort-object-types.ts
rules/sort-sets.ts
test/rules/sort-array-includes.test.ts
test/rules/sort-jsx-props.test.ts
test/rules/sort-sets.test.ts

Most lines added are documentation and tests.
This PR adds the following:
- `sort-array-includes`: `newlines-between`.
- `sort-sets`: `netwlines-between`.
- `sort-jsx-props`: `netwlines-between` and `partition-by-newlines`.
Bonus:
- Adds missing documentation in other rules.

feat: adds `newlines-between` to some rules

---

package.json
rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-decorators.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-heritage-clauses.ts
rules/sort-imports.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts
rules/sort-modules.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
test/rules/sort-objects.test.ts
test/rules/sort-variable-declarations.test.ts
utils/get-custom-groups-compare-options.ts
utils/get-newlines-between-option.ts
utils/report-all-errors.ts
utils/should-partition.ts
utils/sort-nodes-by-groups.ts
utils/validate-newlines-and-partition-configuration.ts

Continuation of https://github.com/azat-io/eslint-plugin-perfectionist/pull/445.
This PR further decreases code duplication by putting the error and fixes generation behind a `reportAllErrors` function.
It also creates a `shouldPartitionFunction` that checks both `partitionByComment` and `partitionByNewLine`.
A couple of tests were updated:
Some tests were making a circular dependency:
```ts
let b = a,
a = <any>b;
```
(`b` references `a` and `a` references `b`)
=>
```ts
let b = 'b',
a = <any>b;
```
Commit: [`ee0a819` (#446)](https://github.com/azat-io/eslint-plugin-perfectionist/pull/446/commits/ee0a8196a5be59f90f2002980b0618f2c07829eb#diff-f1654584a631196a4910bc61ab25073e4192b2a755673993e9f45eed2f49464d)
There is a minor difference between how dependency errors were raised in …

refactor: reduces code duplication (2)

---

docs/content/rules/sort-enums.mdx
docs/content/rules/sort-maps.mdx
docs/content/rules/sort-objects.mdx
rules/sort-enums.ts
rules/sort-enums/does-custom-group-match.ts
rules/sort-enums/types.ts
test/rules/sort-enums.test.ts
utils/get-custom-groups-compare-options.ts

This PR adds the following options to `sort-enums`:
- `groups` (no predefined group other than `unknown`)
- `customGroups`:
- `elementNamePattern`
- `elementValuePattern`
- `newlinesBetween`

feat(sort-enums): adds `groups`, `customGroups` and `newlinesBetween`

---

utils/report-errors.ts

Fixes an error from https://github.com/azat-io/eslint-plugin-perfectionist/pull/448.
Some `}` were missing, leading to incorrectly formatted error messages.
Unfortunately, it seems that the ESLint framework does not allow us to precisely test the error message that is returned, so there is no way to add tests to bulletproof this.
Result after:

fix: adds missing `}` in error messages

---

rules/sort-imports.ts
test/rules/sort-array-includes.test.ts
test/rules/sort-classes.test.ts
test/rules/sort-enums.test.ts
test/rules/sort-imports.test.ts
test/rules/sort-interfaces.test.ts
test/rules/sort-intersection-types.test.ts
test/rules/sort-jsx-props.test.ts
test/rules/sort-maps.test.ts
test/rules/sort-modules.test.ts
test/rules/sort-object-types.test.ts
test/rules/sort-objects.test.ts
test/rules/sort-sets.test.ts
test/rules/sort-union-types.test.ts
test/utils/get-newlines-between-option.test.ts
test/utils/is-newlines-between-option.test.ts
utils/get-newlines-between-option.ts
utils/is-newlines-between-option.ts
utils/validate-groups-configuration.ts
utils/validate-newlines-and-partition-configuration.ts

Resolves #449.
ℹ️ Don't be afraid of the lines changed: a `describe` wrapper has been added around existing tests in [this](https://github.com/azat-io/eslint-plugin-perfectionist/pull/450/commits/d984a553892b5d0ab07a235b6af229c89cc186b2) commit, changing their indentation. No actual test content is changed in this PR.
Most lines added are tests.
This PR improves the current behavior of the `newlinesBetween` option within `groups` between two groups that are **not** adjacent in the `groups` option.
See the [issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues/449) for two examples of behavior that was incorrect.
The commit with the fix is: [`2fcfb1f` (#450)](https://github.com/azat-io/eslint-plugin-perfectionist/pull/450/commits/a320d09f1b94a3538eafd49ddd3616f7a7dc05a8). …

feat: improves `newlinesBetween` inside `groups` option behavior

---

rules/sort-decorators.ts
rules/sort-heritage-clauses.ts
rules/sort-imports.ts
rules/sort-jsx-props.ts
rules/sort-union-types.ts
test/utils/validate-generated-groups-configuration.test.ts
test/utils/validate-groups-configuration.test.ts
test/utils/validate-newlines-between-inside-groups.test.ts
utils/validate-generated-groups-configuration.ts
utils/validate-groups-configuration.ts
utils/validate-newlines-between-inside-groups.ts
utils/validate-no-duplicated-groups.ts

In [`0cf5540` (#435)](https://github.com/azat-io/eslint-plugin-perfectionist/pull/435/commits/0cf5540a56c7e0e1a18ff6bef96890603529884b), we added a validation step to ensure that users would not enter consecutive `newlinesBetween` inside the `groups` option.
This works, but there are cases where this validation was not applied:
- ✅ `validateGroupsConfiguration` validates this (`sort-imports`, `sort-decorators`, etc).
- ❌ `validateGeneratedGroupsConfiguration` doesn't (`sort-classes`, `sort-objects`, etc).
The first 2 commits refactor the code to extract a `validateNewlinesBetweenInsideGroups` function that we will then use in `validateGeneratedGroupsConfiguration`.

feat: adds missing `newlinesBetween` validation in `groups`

---

test/utils/compare.test.ts
utils/compare.ts

Fixes #472
Duplicate entries can lead to a maximum call stack size error when using `fallbackSort`.
This PR fixes this bug.
- Only happens when users write duplicate entries.
- Should only happen for `exports`.
- Relatively low chance of happening.
-  Linked to a new feature.
=> Low criticality level.

fix: fix maximum call stack size with fallback sort

---

docs/content/rules/sort-interfaces.mdx
docs/content/rules/sort-object-types.mdx
rules/sort-object-types.ts
rules/sort-object-types/get-custom-groups-compare-options.ts
rules/sort-object-types/types.ts
test/rules/sort-interfaces.test.ts
test/rules/sort-object-types.test.ts
test/rules/sort-object-types/get-custom-groups-compare-options.test.ts
test/utils/compare.test.ts
test/utils/sort-nodes-by-groups.test.ts
test/utils/sort-nodes.test.ts
types/common-options.ts
utils/common-json-schemas.ts
utils/compare.ts
utils/sort-nodes-by-groups.ts
utils/sort-nodes.ts

Follow-up of https://github.com/azat-io/eslint-plugin-perfectionist/pull/457, https://github.com/azat-io/eslint-plugin-perfectionist/pull/469 and https://github.com/azat-io/eslint-plugin-perfectionist/pull/474.
Should fully resolve https://github.com/azat-io/eslint-plugin-perfectionist/issues/68 now.
This final PR adds the following options to `sort-objects` and `sort-interfaces`.
- `fallbackSort.sortByValue`.
- `customGroups.fallbackSort.sortByValue`.
```json
{
"groups": [
"unknown",
"metaProperties"
],
"customGroups": [
{
"type": "line-length",
"groupName": "metaProperties",
"elementNamePattern": "^_",
"fallbackSort": {
"type": "alphabetical",
"order": "asc",
"sortBy": "value"
}
}
]
}
```
Enforced result:
```ts
interface Interface {
someNonMetaProperty: any;
// All meta properties below …
```

feat(sort-objects): add `fallbackSort.sortByValue`-related options

---

rules/sort-array-includes.ts
rules/sort-classes.ts
rules/sort-decorators.ts
rules/sort-enums.ts
rules/sort-exports.ts
rules/sort-heritage-clauses.ts
rules/sort-imports.ts
rules/sort-jsx-props.ts
rules/sort-maps.ts
rules/sort-modules.ts
rules/sort-named-exports.ts
rules/sort-named-imports.ts
rules/sort-object-types.ts
rules/sort-objects.ts
rules/sort-switch-case.ts
rules/sort-union-types.ts
rules/sort-variable-declarations.ts
utils/get-source-code.ts

We added support old `getSourceCode` API here:
https://github.com/azat-io/eslint-plugin-perfectionist/issues/101
`context.sourceCode` ESLint API was added here:
https://github.com/eslint/eslint/pull/17107
The old `context.getSourceCode()` API was deprecated in favor of `context.sourceCode` in v8.48.0:
https://github.com/eslint/eslint/releases/tag/v8.40.0 
We currently support ESLint 8.45.0+:
https://github.com/azat-io/eslint-plugin-perfectionist/pull/480
I guess we can remove support for the old API?
N/A.
---

fix: remove deprecated eslint get source code api

---

test/rules/sort-imports.test.ts
utils/compare.ts

Fixes https://github.com/azat-io/eslint-plugin-perfectionist/issues/483
Explicitely writing `fallbackSort` in `sort-imports` will override `sideEffects` which should stay unsorted.
Medium-high:
- Related to a relatively new feature (fallback sorting)
- Requires writing an explicit `fallbackSort` option, meaning that `type` should be `line-length` logically.
- Side-effects import order can break runtime.
=> I think that a hotfix is justified.

fix(sort-imports): fix explicit `fallbackSort` overriding side-effects

---

index.ts

This PR adds meta data to plugin.
~Root `name` field is changed to `packageName` as ESLint recommended use npm package name as the meta name.~
Root `name` field is removed as it's deprecated and replaced by `meta.name`.
- https://eslint.org/docs/latest/extend/plugins#meta-data-in-plugins
---

feat: export plugin meta data

---

rules/sort-objects.ts
test/rules/sort-objects.test.ts

Fixes #491.
This PR fixes dependencies in object destructuring not being detected.

fix(sort-objects): fix object destructuring dependencies not detected

---

test/utils/matches.test.ts
utils/common-json-schemas.ts
utils/matches.ts

- Issue: https://github.com/azat-io/eslint-plugin-perfectionist/issues/488
- Alternative PR: https://github.com/azat-io/eslint-plugin-perfectionist/pull/489
This PR throws a custom error when a RegExp option is entered instead of a string.
In the next major version, the error can be added on the JSON schema level.

fix: throw an error if RegExp expressions are entered

---

test/rules/sort-array-includes.test.ts
test/rules/sort-classes.test.ts
test/rules/sort-decorators.test.ts
test/rules/sort-enums.test.ts
test/rules/sort-exports.test.ts
test/rules/sort-heritage-clauses.test.ts
test/rules/sort-imports.test.ts
test/rules/sort-interfaces.test.ts
test/rules/sort-intersection-types.test.ts
test/rules/sort-jsx-props.test.ts
test/rules/sort-maps.test.ts
test/rules/sort-modules.test.ts
test/rules/sort-named-exports.test.ts
test/rules/sort-named-imports.test.ts
test/rules/sort-object-types.test.ts
test/rules/sort-objects.test.ts
test/rules/sort-sets.test.ts
test/rules/sort-union-types.test.ts
test/rules/sort-variable-declarations.test.ts
utils/compare.ts
utils/report-all-errors.ts

- Issue: https://github.com/azat-io/eslint-plugin-perfectionist/issues/483 (one of the two bugs of that issue)
Some `eslint-disable` errors are raised when they should not in specific situations due to a missing condition.
Low:
- Not related to a new feature.
- Only happens in specific situations.
- Can be bypassed by moving elements around in the worst case.
```ts
interface Test {
b: string;
c: string;
// eslint-disable-next-line
a: string;
}
```
This currently raises an unfixable error.

fix: fix false positive eslint-disable errors raised

---

docs/content/rules/sort-exports.mdx
docs/content/rules/sort-sets.mdx
rules/sort-array-includes.ts
rules/sort-exports.ts
rules/sort-exports/does-custom-group-match.ts
rules/sort-exports/types.ts
rules/sort-object-types.ts
rules/sort-objects.ts
test/rules/sort-exports.test.ts

- Request from https://github.com/azat-io/eslint-plugin-perfectionist/issues/479#issue-2898499262
> PS: We would love to see groups extended to sort-exports as well, especially once this feature is supported 👍
This PR adds the following options to `sort-exports`:
- `groups`
- `customGroups` (new API)
- `newlinesBetween`
It also deprecates `groupKind` for `groups`.
- Allowed selectors: `export`.
- Allowed modifiers: `value`, `type`.
Example:
- `value-export`.
- `type-export`.
The `customGroups` option supports `elementNamePattern`.

feat(sort-exports): add `groups`-related options

---

docs/content/rules/sort-array-includes.mdx
docs/content/rules/sort-enums.mdx
docs/content/rules/sort-exports.mdx
docs/content/rules/sort-jsx-props.mdx
docs/content/rules/sort-maps.mdx
docs/content/rules/sort-sets.mdx
rules/sort-jsx-props.ts
rules/sort-jsx-props/does-custom-group-match.ts
rules/sort-jsx-props/types.ts
test/rules/sort-jsx-props.test.ts

- Resolves partially https://github.com/azat-io/eslint-plugin-perfectionist/issues/493
This PR allows `sort-jsx-props` to handle the new `customGroups` API.
- `prop`
- [DEPRECATED] `multiline`: allows keeping the existing `multiline` group.
- [DEPRECATED] `shorthand`: allows keeping the existing `shorthand` group.
- `multiline`
- `shorthand`
The old `customGroups` object-based API is still handled.
Handles:
- `elementNamePattern`.
- `elementValuePattern`: can match arrow functions with `"\(\s*.*\s*\)\s*=>"`
- Detecting function expressions in JSX props is not straightfoward: it requires us to use the RegExp above. I haven't put a `method` selector in this PR yet.

feat(sort-jsx-props): migrate `groups`-related option to new API

---

test/rules/sort-array-includes.test.ts
test/rules/sort-classes.test.ts
test/rules/sort-enums.test.ts
test/rules/sort-exports.test.ts
test/rules/sort-imports.test.ts
test/rules/sort-interfaces.test.ts
test/rules/sort-intersection-types.test.ts
test/rules/sort-jsx-props.test.ts
test/rules/sort-maps.test.ts
test/rules/sort-modules.test.ts
test/rules/sort-object-types.test.ts
test/rules/sort-objects.test.ts
test/rules/sort-sets.test.ts
test/rules/sort-union-types.test.ts
test/utils/get-newlines-between-option.test.ts
test/utils/validate-custom-sort-configuration.test.ts
test/utils/validate-newlines-and-partition-configuration.test.ts
utils/get-newlines-between-option.ts

Fixes #501
When two elements belong to different groups, we check all the `newlinesBetween` options in-between those groups to deduce if we should enforce a newline behavior or not.
A case was missing: when all in-between elements have `newlinesBetween: never`, we should enforce no newline.
Low:
- Does not affect build/runtime.
- Appears in quite specific cases.

fix: fix invalid `newlinesBetween` result enforced

---

rules/sort-objects.ts
test/rules/sort-objects.test.ts

- Fixes #516
This PR simply applies the `styledComponents` detection to nested objects.

fix(sort-objects): fix nested objects not impacted by `styledComponents`

---

docs/content/rules/sort-imports.mdx
rules/sort-imports.ts
rules/sort-imports/types.ts
test/rules/sort-imports.test.ts

- Follow-up of https://github.com/azat-io/eslint-plugin-perfectionist/pull/505.
- Related to the following issues:
- https://github.com/azat-io/eslint-plugin-perfectionist/issues/494.
- https://github.com/azat-io/eslint-plugin-perfectionist/issues/510.
This PR adds a `value` modifier alongside an `import` selector in order for the `groups` option not to rely on deprecated selectors.
This selector has the lowest priority of all selectors and will match every import.
Similar to the `type` modifier. Any non-`type` import will have the `value` modifier, even `side-effect` imports.
No input/output impact. Only error messages had to be updated.

feat(sort-imports): update default groups to new API

---

rules/sort-classes.ts
rules/sort-enums.ts
rules/sort-imports.ts
rules/sort-imports/types.ts
rules/sort-modules.ts
rules/sort-objects.ts
rules/sort-variable-declarations.ts
test/rules/sort-imports.test.ts
test/utils/compute-nodes-in-circular-dependencies.test.ts
test/utils/is-node-dependent-on-other-node.test.ts
utils/compute-nodes-in-circular-dependencies.ts
utils/is-node-dependent-on-other-node.ts
utils/report-all-errors.ts
utils/sort-nodes-by-dependencies.ts

- Fixes https://github.com/azat-io/eslint-plugin-perfectionist/issues/513.
- Waiting for https://github.com/azat-io/eslint-plugin-perfectionist/pull/505 to be merged before opening.
In typescript projects targetting Node.js, typescript import-equals re-order may result in runtime errors due to usage before initialization.
```ts
import a = aImport.a1.a2;
import aImport from "b";
```
```ts
import a = aImport.a1.a2;
import * as aImport from "b";
```
```ts
import a = aImport.a1.a2;
import { aImport } from "b";
```

fix(sort-imports): fix undetected typescript import-equals dependencies

---

docs/content/rules/sort-imports.mdx
rules/sort-imports.ts
rules/sort-imports/types.ts
test/rules/sort-imports.test.ts
test/utils/validate-generated-groups-configuration.test.ts
utils/validate-generated-groups-configuration.ts

In [`62c5c62` (#505)](https://github.com/azat-io/eslint-plugin-perfectionist/pull/505/commits/62c5c621162bc2102c9890d5f450594259eed33d), the `object` group/selector was deprecated as it was never matched.
The previous documentation had this description:
https://github.com/azat-io/eslint-plugin-perfectionist/blob/f7907794ea899e1deae3f75de77b965bb3d09d5a/docs/content/rules/sort-imports.mdx?plain=1#L309
This PR does two things:
- It adds a `ts-equals` modifier that matches those objects.
- It prevents non-external reference ts import-equals imports from matching `external`:
- `import log = console.log` currently matches `external` (it was matching `unknown` before https://github.com/azat-io/eslint-plugin-perfectionist/pull/508), but this syntax can also match internal imports (see the second …

feat(sort-imports): add back `ts-equals` (`object` group) modifier

---

docs/content/rules/sort-imports.mdx
rules/sort-imports.ts
rules/sort-imports/compute-common-selectors.ts
rules/sort-imports/matches-tsconfig-paths.ts
rules/sort-imports/types.ts
test/rules/sort-imports.test.ts
test/rules/sort-imports/compute-common-selector.test.ts
test/rules/sort-imports/matches-tsconfig-paths.test.ts

- Follow-up of https://github.com/azat-io/eslint-plugin-perfectionist/pull/511.
- Resolves https://github.com/azat-io/eslint-plugin-perfectionist/issues/510.
- Resolves https://github.com/azat-io/eslint-plugin-perfectionist/issues/494.
- Resolves https://github.com/azat-io/eslint-plugin-perfectionist/issues/515.
This PR adds the specific selectors and modifiers to `sort-import`:
- `subpath` (https://github.com/azat-io/eslint-plugin-perfectionist/issues/510)
- The priority of this selector is right below `parent`. 
- `tsconfig-path` (https://github.com/azat-io/eslint-plugin-perfectionist/issues/515)
- The priority of this selector is right below `style`.
- `side-effect`: Side-effect imports.
- `require`: Imports that use `require`.
- `default` …

feat(sort-imports): add `subpath`, `tsconfig-path` selectors and 5 modifiers

---

package.json
pnpm-lock.yaml
rules/sort-imports.ts
test/rules/sort-array-includes.test.ts
test/rules/sort-classes.test.ts
test/rules/sort-decorators.test.ts
test/rules/sort-enums.test.ts
test/rules/sort-heritage-clauses.test.ts
test/rules/sort-imports.test.ts
test/rules/sort-interfaces.test.ts
test/rules/sort-intersection-types.test.ts
test/rules/sort-jsx-props.test.ts
test/rules/sort-maps.test.ts
test/rules/sort-modules.test.ts
test/rules/sort-named-exports.test.ts
test/rules/sort-named-imports.test.ts
test/rules/sort-objects.test.ts
test/rules/sort-sets.test.ts
test/rules/sort-switch-case.test.ts
test/rules/sort-union-types.test.ts
test/rules/sort-variable-declarations.test.ts
test/utils/validate-rule-json-schema.ts
utils/alphabet.ts
utils/is-partition-comment.ts

- Fixes #524
- Fixes #525
The test added in https://github.com/azat-io/eslint-plugin-perfectionist/pull/521 does not catch another error that was existing in the JSON schema of `sort-imports`:
The `id` of the JSON schema needs to be placed at the root too.
This PR installs the dev-dependency `ajv-draft-04` and uses it in tests to further strengthen JSON schema validation.
Technically, I think that the `json-schema-to-typescript-lite` dev-dependency and test should not be needed anymore, but I've kept it for safety.
Low: does not prevent linting.

fix(sort-imports): fix json-schema throwing uncaught warning

---

rules/sort-imports.ts

- Fixes https://github.com/azat-io/eslint-plugin-perfectionist/issues/527.
Only affects configurations using the deprecated `customGroups` API.
There are 2 ways to validate groups currently:
- [`validateGeneratedGroupsConfiguration`](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/utils/validate-generated-groups-configuration.ts) for the new API.
- [`validateGroupsConfiguration`](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/utils/validate-groups-configuration.ts) for the old API.
`validateGroupsConfiguration` relies on an array of all allowed predefined groups to work and is not optimized for large allowed groups arrays (which is the case with many selectors and modifiers, as you can permute modifiers as you wish).
This PR makes `sort-imports` use …

perf(sort-imports): use `validateGeneratedGroupsConfiguration`

---

rules/sort-imports.ts
test/utils/validate-rule-json-schema.ts

- Fixes #529
`sort-imports` JSON schema was recently updated to allow an array of configurations to be passed (useful when we want to match elements and not sort them with `type: 'unsorted'`).
Its JSON schema is also more complex than other rules as it has the following definitions: 
- `is-line-length` to check that if the configuration is `line-length`.
- `max-line-length-requires-line-length-type` to ensure that the `maxLineLength` option is only passed when `type` is `line-length`.
For some reason, this makes `eslint-typegen` fail to generate accurate Typescript types.
This PR removes those two JSON Schema definitions and adds a simple test to check whether the generated Typescript is correct. 
<details>
<summary>Generated TS</summary>
```ts
export type Id = {
/**
* Fallback sort …
```

fix(sort-imports): fix weak JSON schema typings generated

---

rules/sort-decorators.ts
rules/sort-enums.ts
rules/sort-heritage-clauses.ts
rules/sort-imports.ts
rules/sort-jsx-props.ts
rules/sort-object-types.ts
rules/sort-objects.ts
test/utils/validate-rule-json-schema.ts
utils/common-json-schemas.ts

This PR contains a mix of various JSON schema related fixes and improvements:
- Fix invalid `fallbackSort` JSON schema (it is passing today due to weak validation: missing `additionalProperties: false`)
- Add a test to check for missing `additionalProperties: false` (which generates `[key: string]: uknown` in typings).
- Improve JSON schema descriptions to match the documentation better.

feat: strengthen JSON schemas

---

docs/content/rules/sort-intersection-types.mdx
docs/content/rules/sort-union-types.mdx
rules/sort-heritage-clauses.ts
rules/sort-intersection-types.ts
rules/sort-union-types.ts
rules/sort-union-types/types.ts
test/rules/sort-intersection-types.test.ts
test/rules/sort-union-types.test.ts
utils/compute-group.ts
utils/get-group-number.ts
utils/is-sortable.ts

This PR:
- migrates the `sort-union-types` and `sort-intersection-types`'s `groups` to the new API.
- adds the `customGroups` option.
There is no functional change: the list of selectors is the same as the list of predefine groups before.

feat(sort-union-types): migrates `groups` to new API

---

test/utils/common-json-schemas.test.ts
utils/common-json-schemas.ts

This PR does the following:
- Adds tests for `common-json-schemas`.
- Strengthen a few JSON schemas by enforcing the following properties:
- Forbid `fallbackSort: {}`.
- Forbid `{}` objects inside `groups`.
- Forbid `{}` in `{ pattern: string; flags?: string }` RegExp objects.
- Forbid `partitionByComment: {}`.
- Enforce `groupName` in `customGroups` array objects.

test: add additional JSON schema tests

---

docs/content/rules/sort-imports.mdx
rules/sort-imports.ts
rules/sort-imports/read-closest-ts-config-by-path.ts
rules/sort-imports/types.ts
test/rules/sort-imports.test.ts
test/rules/sort-imports/read-closest-ts-config-by-path.test.ts

- Resolves #536
This PR:
- Adds an option `tsconfig: { rootDir: string; filename?: string}`.
- If `filename` is not entered, will search for the closest `tsconfig.json` file.
- Deprecates `tsconfigRootDir`.

feat(sort-imports): allow to find alternate `tsconfig` file

---

docs/content/rules/sort-imports.mdx
rules/sort-imports.ts
rules/sort-imports/types.ts
test/rules/sort-imports.test.ts

The `tsconfigRootDir` option has been replaced with the `tsconfig` object option, which also includes an optional `filename` attribute.

feat(sort-imports)!: drop deprecated `tsconfigRootDir` support

---

docs/content/rules/sort-objects.mdx
rules/sort-objects.ts
rules/sort-objects/types.ts
test/rules/sort-objects.test.ts

In favor of `objectDeclarations` and `destructuredObjects`.
Ideally, I think that those two settings should be `useConfigurationIf` options.

feat(sort-object)!: drop deprecated `destructureOnly` option

---

docs/content/rules/sort-enums.mdx
rules/sort-enums.ts
rules/sort-enums/types.ts
test/rules/sort-enums.test.ts

- Resolves https://github.com/azat-io/eslint-plugin-perfectionist/issues/564
This PR addresses 3 points of the `sort-enums` rule.
There are 2 options used to control sorting by value today:
- `sortByValue: boolean`.
- If `true`, will always sort by value.
- `forceNumericSort: boolean`.
- If `true`, will sort by value if the enum is numeric.   
Those two options can be simply merged into:
`sortByValue: boolean | "ifNumericEnum"`.
When detecting if an enum value is a number, we ignore the fact that expressions such as `NaN | 42` result in `42`.
The case happens in enums such as
```ts
enum Enum {
A = 1,
B = 2,
C = A << 2 // A is considered as NaN, so the result will be considered as 0, but it should be 4 in reality if we could parse that A is 1
}
```
- Request from …

feat(sort-enums)!: replace `forceNumericSort` and update default `sortByValue` option

---

rules/sort-variable-declarations.ts
test/rules/sort-variable-declarations.test.ts

- Fix #594
Simply fix the bug !
> [!CAUTION]
> Merging toward **main**.
> - The merge afterward toward `next` shouldn't cause conflicts.
> - We can release a new minor version for V4 if needed.
It's probably not a common variable declaration style.

fix(594): fix destructured assignments dependencies not detected
