- rules/sort-imports.ts
- test/sort-imports.test.ts
Support `require()` in `sort-imports` rule
#32 
---
> feat: support require by sort-imports rule

- docs/rules/index.md
- docs/rules/sort-vue-attributes.md
- index.ts
- package.json
- pnpm-lock.yaml
- readme.md
- rules/sort-vue-attributes.ts
- test/sort-vue-attributes.test.ts
Add new `sort-vue-attributes` rule.
#25, #32
---
> feat: add sort-vue-attributes rule

- docs/rules/sort-imports.md
> docs: add missing comma in sort-imports usage example

- test/sort-interfaces.test.ts
> fix(sort-interfaces): fix logic error in test case

- docs/rules/sort-interfaces.md
- rules/sort-interfaces.ts
- test/sort-interfaces.test.ts
> chore: convert `optionalityOrder` to kebab case

- rules/sort-exports.ts
- test/sort-exports.test.ts
> fix(sort-exports): work with star exports

- docs/rules/sort-intersection-types.md
fix information about version introduction
close #133
---
> docs(sort-intersection-types): fix information about version introduction

- index.ts
- test/sort-array-includes.test.ts
- test/sort-astro-attributes.test.ts
- test/sort-classes.test.ts
- test/sort-enums.test.ts
- test/sort-exports.test.ts
- test/sort-imports.test.ts
- test/sort-interfaces.test.ts
- test/sort-intersection-types.test.ts
- test/sort-jsx-props.test.ts
- test/sort-maps.test.ts
- test/sort-named-exports.test.ts
- test/sort-named-imports.test.ts
- test/sort-object-types.test.ts
- test/sort-objects.test.ts
- test/sort-svelte-attributes.test.ts
- test/sort-union-types.test.ts
- test/sort-vue-attributes.test.ts
Simplify test cases to improve their maintenance.
N/A.
---
> test: simplify test cases

- configs/recommended-alphabetical.ts
- configs/recommended-line-length.ts
- configs/recommended-natural.ts
- docs/content/configs/recommended-alphabetical.mdx
- docs/content/configs/recommended-line-length.mdx
- docs/content/configs/recommended-natural.mdx
- index.ts
- package.json
- readme.md
- vite.config.ts
Make a new config export according to ESLint recommendations.
https://github.com/eslint/eslint/issues/18095
---
> feat!: make new config export

- docs/content/rules/sort-switch-case.mdx
- index.ts
- readme.md
- rules/sort-switch-case.ts
- test/sort-switch-case.test.ts
- typings/index.ts
Add new rule `sort-switch-case`.
#54 
---
> feat: add sort-switch-case rule

- index.ts
- package.json
- pnpm-lock.yaml
- vite.config.ts
Adds TypeScript types.
https://github.com/eslint/eslint/issues/18093
https://github.com/eslint/rfcs/pull/117
---
> feat: add typescript types

- docs/content/rules/sort-classes.mdx
- rules/sort-classes.ts
- test/sort-classes.test.ts
Adds support for ordering protected properties and methods in a class.
---
> feat: support for ordering protected properties and methods in classes

- package.json
- pnpm-lock.yaml
- rules/sort-enums.ts
- rules/sort-jsx-props.ts
- test/fixtures/tsconfig.json
- test/sort-array-includes.test.ts
- test/sort-astro-attributes.test.ts
- test/sort-classes.test.ts
- test/sort-enums.test.ts
- test/sort-exports.test.ts
- test/sort-imports.test.ts
- test/sort-interfaces.test.ts
- test/sort-intersection-types.test.ts
- test/sort-jsx-props.test.ts
- test/sort-maps.test.ts
- test/sort-named-exports.test.ts
- test/sort-named-imports.test.ts
- test/sort-object-types.test.ts
- test/sort-objects.test.ts
- test/sort-svelte-attributes.test.ts
- test/sort-switch-case.test.ts
- test/sort-union-types.test.ts
- test/sort-variable-declarations.test.ts
- test/sort-vue-attributes.test.ts
Upgrade to TypeScript ESLint v8 and ESLint v9
N/A.
---
> feat: move to typescript-eslint v8

- rules/sort-enums.ts
- test/sort-enums.test.ts
> fix: #264: Template literal expressions are not detected as dependencies

- docs/content/rules/sort-exports.mdx
- docs/content/rules/sort-objects.mdx
- rules/sort-classes.ts
- rules/sort-enums.ts
- rules/sort-exports.ts
- rules/sort-objects.ts
> chore: correct partitionByComment description

- docs/content/rules/sort-interfaces.mdx
- rules/sort-interfaces.ts
- test/sort-interfaces.test.ts
- utils/get-node-range.ts
> feat(sort-interfaces): add partitionByComment option

- rules/sort-switch-case.ts
- test/sort-switch-case.test.ts
Fixes #313. 
- Fixes break statements not being recognized.
- Adds tests.
> fix(sort-switch-case): #313: fixes break statements not being recognized

- docs/content/guide/introduction.mdx
- readme.md
Commit 99a7e3376395e296f00702695bd1c3334cf9a447 renamed the license file. This PR adjusts sources to changes.
---
> fix: update license reference

- docs/content/configs/recommended-alphabetical.mdx
- docs/content/guide/introduction.mdx
- docs/content/rules/sort-array-includes.mdx
- docs/content/rules/sort-classes.mdx
- docs/content/rules/sort-decorators.mdx
- docs/content/rules/sort-enums.mdx
- docs/content/rules/sort-exports.mdx
- docs/content/rules/sort-heritage-clauses.mdx
- docs/content/rules/sort-imports.mdx
- docs/content/rules/sort-interfaces.mdx
- docs/content/rules/sort-intersection-types.mdx
- docs/content/rules/sort-jsx-props.mdx
- docs/content/rules/sort-maps.mdx
- docs/content/rules/sort-named-exports.mdx
- docs/content/rules/sort-named-imports.mdx
- docs/content/rules/sort-object-types.mdx
- docs/content/rules/sort-objects.mdx
- docs/content/rules/sort-sets.mdx
- docs/content/rules/sort-switch-case.mdx
- docs/content/rules/sort-union-types.mdx
- docs/content/rules/sort-variable-declarations.mdx
- readme.md
- Commit **1**: Fixes grammatical/syntax mistakes
- Commit **2**: Readability improvements
- Commit **3**: Adds link to `localeCompare` for `alphabetical` type
- Commit **4**: Adds link to `natural-compare-lite` for `natural` type
- Commit **5**: Fixes `ignoreCase: false` documentation (https://github.com/azat-io/eslint-plugin-perfectionist/issues/344#issuecomment-2443465878)
> docs: Documentation improvements

- docs/content/rules/sort-array-includes.mdx
- docs/content/rules/sort-classes.mdx
- docs/content/rules/sort-decorators.mdx
- docs/content/rules/sort-enums.mdx
- docs/content/rules/sort-exports.mdx
- docs/content/rules/sort-heritage-clauses.mdx
- docs/content/rules/sort-imports.mdx
- docs/content/rules/sort-interfaces.mdx
- docs/content/rules/sort-intersection-types.mdx
- docs/content/rules/sort-jsx-props.mdx
- docs/content/rules/sort-maps.mdx
- docs/content/rules/sort-modules.mdx
- docs/content/rules/sort-named-exports.mdx
- docs/content/rules/sort-named-imports.mdx
- docs/content/rules/sort-object-types.mdx
- docs/content/rules/sort-objects.mdx
- docs/content/rules/sort-sets.mdx
- docs/content/rules/sort-switch-case.mdx
- docs/content/rules/sort-union-types.mdx
- docs/content/rules/sort-variable-declarations.mdx
> fix doc v4

- rules/sort-modules.ts
> fix: fixes invalid import

- test/rules/sort-imports/read-closest-ts-config-by-path.test.ts
Fixes test not passing in #425.
> fix: fixes test in "improve folder structure" PR (#425)

- docs/content/guide/getting-started.mdx
- package.json
- readme.md
- Related issue: https://github.com/azat-io/eslint-plugin-perfectionist/issues/456
- Related comment: https://github.com/azat-io/eslint-plugin-perfectionist/issues/456#issuecomment-2706584769
This PR update the `eslint` peer-dependency to `>=8.45.0` and the documentation based on the investigation [here](https://github.com/azat-io/eslint-plugin-perfectionist/issues/456#issuecomment-2625555105).
> chore: update `eslint` peer dependency version

- test/rules/sort-imports.test.ts
- utils/get-comments-before.ts
Fixes #539.
This PR makes comment fixes ignore shebang comments.
> fix: ignore Shebang comments

- docs/content/rules/sort-imports.mdx
- rules/sort-imports.ts
- test/rules/sort-imports.test.ts
> feat(sort-imports): use @/ as internal import pattern by default

- package.json
- vite.config.ts
Move to ESM only.
https://github.com/azat-io/eslint-plugin-perfectionist/issues/566
---
> feat!: move to esm only
